# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mome',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
